kind: ConfigMap
apiVersion: v1
data:
  schema-version:
    v1
  config-version:
    v1
  prometheus-data-collection-settings: |-
    # Custom Prometheus metrics data collection settings
    [prometheus_data_collection_settings.cluster]
        interval = "1m"
        monitor_kubernetes_pods = true
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
  annotations:
    openshift.io/reconcile-protect: "true"